# Railway configuration file
# This file defines the relationships between services

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Pre-start script to fix PostgreSQL configuration
preStartCommand = "node railway-db-fix.js"

[env]
DATABASE_URL = "${RAILWAY_POSTGRESQL_CONNECTION_URL}"
# Disable any custom parameters that might be causing issues
PG_CUSTOM_PARAMS = "false"

# Define the relationship with the PostgreSQL database
[[services]]
name = "postgresql"
# Ensure we're using standard PostgreSQL configuration
[services.config]
standard_conforming_strings = "on"